# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_auto_20160531_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento_saida',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='controle.Cliente'),
            preserve_default=False,
        ),
    ]
