# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_medicamento_saida_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medicamento_entrada',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicamento_saida',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
