# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_remove_medicamento_cod_barra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento_saida',
            name='lote',
        ),
    ]
