# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0006_remove_medicamento_saida_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
