# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0011_auto_20160706_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento_entrada',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controle.Usuario'),
        ),
    ]
