# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0012_auto_20160901_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento_entrada',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controle.Lote'),
        ),
    ]
